language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t codingmaven/learndocker -f Dockerfile.dev .
script:
    - docker run -e CI=true codingmaven/learndocker npm run test -- --coverage
